### ISSUE TITLE
After installing on Linux, start a new shell

### ISSUE THREAD

**Issue by peter-kehl** [deta/space-docs#142]
Hi at Deta.

1. Local machine: x64 Linux: current Manjaro (stable Arch), pretty standard, `bash` in standard GNOME Terminal app.
2. Successfully installed Following https://deta.space/docs/en/build/new-apps#installing-the-space-cli > "Linux" tab (from within `bash` in GNOME Terminal).
3. Problem: Can't run `space login` (or `space anything-here`) in that very same bash. `space` was not on `$PATH` yet. I did NOT have to close & restart whole Terminal, neither to open any new Terminal window. I did work in a new Terminal tab (even within that same Terminal window).

Please update https://deta.space/docs/en/build/new-apps#installing-the-space-cli to reflect that.

(We most likely don't want people to re-apply `~/.bashrc` like `source ~/.bashrc`, as that may mess up aliases...) Thank you in advance.

**Comment by MaximilianHeidenreich** [comment]
@abdelhai We could definitely add an info box inside the docs, but I think we can solve this issue better by just adding to the PATH variable manually after a successful installation. This will make space available inside the current shell instantly.

**Comment by MaximilianHeidenreich** [comment]
Closed as we have added additional information inside the installation section of the CLI docs.
See #170 for reference.
