### ISSUE TITLE
Migration guide has an incorrect example

### ISSUE THREAD

**Issue by teddiur** [deta/space-docs#17]
On the "Create an Environment Variable" section of the "Migrate a Micro" guide there's an incorrect example, saying that `env` should be in the same identation level as `engine`, but it should be nested in `presets`.

I tried to make a branch and push to this repo but got 403 denied. Is there any way that I can contribute?

**Comment by abdelhai** [comment]
you could give us the link to the issue.
to be able to contribute directly, you could open a pull request. check out this guide from GitHub https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by TychoLex42** [comment]
I have addressed this with his pull request:
https://github.com/deta/space-docs/pull/21

**Comment by teddiur** [comment]
Thanks @abdelhai for the time to send me this guide and @TychoLex42 for the PR!
