### ISSUE TITLE
Switch to Content Collections

### ISSUE THREAD

**Issue by aarushthukral** [deta/space-docs#45]
Astro v2.0 introduced [content collections](https://astro.build/blog/introducing-content-collections/), a type-safe markdown interface.

Astro v2.1 also added in-built support for [image optimization](https://astro.build/blog/astro-210/#built-in-image-support) via the `src/assets` directory.

In addition to improving website performance, content collections can also simplify the development process by providing a more intuitive way to organize and manage content, leading to faster development time and easier maintenance in the long run.

**Comment by abdelhai** [comment]
i think we tried be we found out our current code is incompatible with v2.x
cc @mikBighne98

**Comment by mikBighne98** [comment]
this week @aarushthukral 🤞
