### ISSUE TITLE
How does your python WSGI/ASGI server work?

### ISSUE THREAD

**Issue by kumkee** [deta/space-docs#48]
In your [documentation](https://deta.space/docs/en/quickstart-guides/python), you mentioned 

> For Space, you do not need to use a server like uvicorn, as Space has its own global server.

I am trying to build a backend connecting SuperTokens' core. It works with local uvicorn but not on Space.
Here is [the issue I filed on SuperTokens](https://github.com/supertokens/supertokens-python/issues/296). Can you look into that as well, please?

### Summary of what I wrote there:
- Deta Space doesn't use a server like `uvicorn` but has its [own global server](https://files.deta.dev/opt/python/detalib/), which might be causing the issue.
- The live UM dashboard can be accessed on this URL: https://stokensdemo-1-z8458742.deta.app/auth/dashboard where you can see the errors.
- My code is listed in my [SupertokensElm repo](https://github.com/kumkee/SupertokensElm) under the [backend directory](https://github.com/kumkee/SupertokensElm/tree/supertokens/backend).

### Which Repo?
Since you don't host your server code here on GitHub, I don't know which repo of yours to report my issue to. It is about how your engine works so I am posting it here in your documentation. Let me know if there is somewhere else more appropriate.

**Comment by kumkee** [comment]
@abdelhai agrees to investigate into the issue. I am reopening it.

**Comment by mikBighne98** [comment]
Hey @kumkee, sorry for the delay in response. I see that you are trying to use custom run commands for your Python app on Space.
As said [here](https://github.com/supertokens/supertokens-python/issues/296#issuecomment-1468908297), as of now the Python runtime on Space does not support custom run commands, but we are working on adding this feature in the near future. In the meantime, your app must be an instance of ASGI or WSGI (like FastAPI or Flask) with the app instance named `app`, when running on the Python runtime. Take a look at [this](https://github.com/deta/starters/tree/main/python-app) for reference.

Also I see [here](https://github.com/kumkee/SupertokensElm/blob/ca2ab8b7a7fc325f54f81765d7c4f368993affcc/Spacefile#L8), you have specified the port to 80. Please note that you need to make your server app listen to the port specified in the PORT environment variable of Micros, which is currently set to 8080.

**Comment by mikBighne98** [comment]
Creating a new event loop and setting it as the current event loop seems to have solved the problem:
```python
import asyncio
# rest of the code
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```
Please try this and let us know if this resolves your issue :)

**Comment by kumkee** [comment]
@mikBighne98, thank you.

> as of now the Python runtime on Space does not support custom run commands

I didn't intent to `run` commands under the `python3.9` engine. It was an experiment with the SuperTokens team in an attempt to solve my problem.

The [default branch](https://github.com/kumkee/SupertokensElm/tree/deta) has now been rolled back to the state without those custom commands or run sections. 

> Creating a new event loop and setting it as the current event loop seems to have solved the problem:

The suggested code is added under [the asynico branch](https://github.com/kumkee/SupertokensElm/tree/asyncio). 

Both cases still give me errors:
```
Error Type:
Runtime.ExitError

Error Message:
RequestId: b1a5c903-8fde-4a3a-921a-7079ee1985ed Error: Runtime exited with error: exit status 127

Logs:
time="2023-03-15T18:26:19Z" level=info msg="serving logs listener on sandbox.localdomain:1234" agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Subscribed	Types: [Function]
/opt/bootstrap: does not exist
```
The [live app](https://stokensdemo-1-z8458742.deta.app/) is with the asyncio branch at the moment.

**Comment by mikBighne98** [comment]
I just redeployed using the exact same source code of [backend under the asyncio branch](https://github.com/kumkee/SupertokensElm/tree/asyncio/backend). Just commented [this](https://github.com/kumkee/SupertokensElm/blob/asyncio/backend/main.py#L5) and replaced the API keys and client secret with random strings as I don't have those. And it successfully deployed and returned `{"message":"Hello World"}` when I accessed the endpoint. I don't see anything wrong in your Spacefile also. Make sure you're deploying the source code from the right branch and if it still persists try to change the micro name maybe. But do let us know :)

**Comment by kumkee** [comment]
> ... replaced the API keys and client secret with random strings as I don't have those. And it successfully deployed and returned `{"message":"Hello World"}` ...

With random keys, python would ignore the `init(...)` part I guess, which has been the cause of the problem.
Let me publicise (or share with) the secret file later today (I'm going away from my PC).
With successfully running the `init()` part, you would be able to access the `/auth/dashboard` path of the endpoint as well.

**Comment by kumkee** [comment]
> > ... replaced the API keys and client secret with random strings as I don't have those. And it successfully deployed and returned `{"message":"Hello World"}` ...
> 
> With random keys, python would ignore the `init(...)` part I guess, which has been the cause of the problem. Let me publicise (or share with you) the secret file later today (I'm going away from my PC). With successfully running the `init()` part, you would be able to access the `/auth/dashboard` path of the endpoint as well.

@mikBighne98 The [secret keys are now published](https://github.com/kumkee/SupertokensElm/tree/asyncio/backend).
Very weirdly, I can no longer push to the project. space-cli says `Error: failed to push code, unauthorized`. Is it because you are using it as well?

**Comment by kumkee** [comment]
> Unless you want to find out why the old space-project corrupts, ...

I guess this is worth opening another issue but this doesn't concern me as a user. I am closing the issue now.

Thank you @mikBighne98, @abdelhai and the rest of the Deta team. Although it is in beta with some problems, your support makes my experience with Deta Space more enjoyable.

**Comment by mikBighne98** [comment]
Thanks a lot for your kind words, @kumkee. We are actively working on fixing these issues and improving the deployment process.
> Unless you want to find out why the old space-project corrupts

We have received several reports regarding this. We are investigating the cause and will try to resolve it as soon as possible.

> By the way, is there a way to delete a space-project?

As of now, there is no way to delete a project, but we plan to add this feature in the near future.
