### ISSUE TITLE
Rust App build time error: cargo: command not found

### ISSUE THREAD

**Issue by kumkee** [deta/space-docs#53]
Following the [Run a Rust App](https://deta.space/docs/en/quickstart-guides/rust) quick start guide gives me the following error:
```
/bin/bash: cargo: command not found
```

The problem was first raised in December 2022 on Discord but no solution has yet been provided.

Please update the docs with a working tutorial.

**Comment by abdelhai** [comment]
this issue has been fixed and the guide was updated. please let me know if you get any other errors
guide: https://deta.space/docs/en/quickstart-guides/rust
