### ISSUE TITLE
Doc says deta is installed on Micro. It is, but it's outdated.

### ISSUE THREAD

**Issue by tobiasbp** [deta/space-docs#67]
While it is true that: "If you are using Deta Base within a Deta Micro, the Deta SDK comes pre-installed..." the version may be outdated, and not match the functionality in the current docs. Maybe the user should be told to update to the latest version, or pin to the requested version?
 
https://deta.space/docs/en/reference/base/sdk#instantiating

**Comment by abdelhai** [comment]
thanks for pointing this out. should be fixed with pr https://github.com/deta/space-docs/pull/68
